local H = require("screens.grid_helpers")

describe("grid_helpers.is_hidden", function()
  it("regular names", function()
    assert.is_false(H.is_hidden("readme.txt"))
    assert.is_false(H.is_hidden("folder"))
  end)
  it("dotfiles", function()
    assert.is_true(H.is_hidden(".git"))
  end)
  it("nil/empty", function()
    assert.is_false(H.is_hidden(nil))
    assert.is_false(H.is_hidden(""))
  end)
end)

describe("grid_helpers.parent_of", function()
  it("root", function()
    assert.are.equal("/", H.parent_of("/"))
  end)
  it("strips trailing slash", function()
    assert.are.equal("/home/user", H.parent_of("/home/user/"))
  end)
  it("up one level", function()
    assert.are.equal("/home/user", H.parent_of("/home/user/file.txt"))
  end)
end)

describe("grid_helpers.basename", function()
  it("last segment", function()
    assert.are.equal("file.txt", H.basename("/home/user/file.txt"))
  end)
end)

describe("grid_helpers.human", function()
  it("zero", function()
    assert.are.equal("0 B", H.human(0))
  end)
  it("kilobytes", function()
    assert.are.equal("1.0 KB", H.human(1024))
  end)
  it("megabytes", function()
    assert.are.equal("1.0 MB", H.human(1024 * 1024))
  end)
end)
